### ISSUE TITLE
SommaCifre

### ISSUE THREAD

**Issue by FabioZTessitore** [Roby1203/helloworld_c#3]
Non puoi usare il 100, solo 10

E non puoi fare due operazioni per 10 nella stessa riga

**Comment by FabioZTessitore** [comment]
nessuna novità?

**Comment by Roby1203** [comment]
Stasera mi ci metto a lavorare..😀😀
Il 23/apr/2017 19:30, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
aggiusta

**Comment by FabioZTessitore** [comment]
aggiusta

**Comment by FabioZTessitore** [comment]
devi ancora aggiustare questo
